name: Generate Snake

on:
  schedule: # runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: vikassaini77
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "dist/*.svg"
