name: Update Last Updated Time

on:
workflow_dispatch:
schedule:
- cron: "0 */1 * * *" # Runs every hour

jobs:
update-readme:
runs-on: ubuntu-latest

```
steps:
  # Step 1: Checkout repository
  - name: Checkout Repository
    uses: actions/checkout@v3

  # Step 2: Get current time
  - name: Get current time
    id: current-time
    uses: 1466587594/get-current-time@v2
    with:
      format: dddd, MMMM D, YYYY, h:mm:ss A Z
      utcOffset: "+05:30"

  # Step 3: Find and Replace
  - name: Find and Replace
    uses: jacobtomlinson/gha-find-replace@v2
    with:
      find: "Last updated: .*"
      replace: "Last updated: ${{ steps.current-time.outputs.formattedTime }}"
      regex: true

  # Step 4: Commit changes
  - name: Commit changes
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: "BOT: Auto-update last modified time"
```
