name: WakaTime Stats

on:
  schedule:
    # Runs every 4 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    # Add this permissions block
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # Required secrets
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Optional inputs
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LINES_OF_CODE: "true"
